//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPG323_P2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int TagID { get; set; }
        public string Description { get; set; }
        public int ImageID { get; set; }
        public int UserID { get; set; }
        public int Date { get; set; }
    
        public virtual Table Table { get; set; }
        public virtual User User { get; set; }
    }
}
